on:
  workflow_dispatch:
    inputs:
      gamepass_id:
        description: 'Enter the Gamepass ID'
        required: true
jobs:
  run-downloader:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Python script
        run: |
          python main.py ${{ github.event.inputs.gamepass_id }}

      - name: Upload result image
        uses: actions/upload-artifact@v4
        with:
          name: gamepass-image
          path: output/
